### ISSUE TITLE
General website cleanup

### ISSUE THREAD

**Issue by ShaneBonkowski** [ShaneBonkowski/ShanesGames#276]
- [x] Play around with font size and box size so that the descriptions fill the content boxes vertically on phone and PC
- [x] Clean up header buttons so that the text is centered vertically (if this doesnt fix it https://github.com/ShaneBonkowski/ShanesGames/issues/275) on phone and the button is not too tall
- [x] Same for footer linkedin button
- [x] Center leader boid  check box text vertically on phone if https://github.com/ShaneBonkowski/ShanesGames/issues/275 doesnt fix it
- [x] Bold the "Alignment", "Cohesion", etc. on the "i" button for better boids game
- [x] Make "black hole reject" larger for phone (maybe computer too)
- [x] Center the text horizontally for flip tile game for input toggles on phone (may need to make sure size of text is optimized for this? Or the bounding boxes for them?)
- [x] Vertically center the flip tile text for the game title on the header if https://github.com/ShaneBonkowski/ShanesGames/issues/275 doesnt fix it
- [x] Make loading... on loading screen a better size and position
- [x] Tweak better boids settings desc text for phone so that there is not a single word to 1 line on the bottom. Smaller text or less words, or maybe bigger text
- [x] Move the toggles for phone and computer version of flip tile to the left more. Closer to the buttons
- [x] Add some spacing to list elements in the privacy policy and cookie policy
- [x] Need to make search bar taller height for computer, since it is not tall enough when phone is horizontal. Text gets fucky
- [x] Shift sliders and help text etc. up for boids settings screen on computer
- [x] toggle labels not horizontally centered on phone in landscape mode for flip tile. But they are for computer?
- [x] Make the leader boid dropdown the same distance below the sliders as the sliders are from one another on PC and phone
- [x] Make search bar very tiny bit smaller in height on phone. Only a little smaller

Do one comprehensive test of all formatting etc. on phone and pc before closing ticket!!!
