### ISSUE TITLE
Short Story Anthology Based on the original Tarot Cards

### ISSUE THREAD

**Issue by ShaneBonkowski** [ShaneBonkowski/ShanesGames#298]
**Create a short story for each tarot card with:**
- Plot elements surrounding their positive and negative meanings. 
- A good (or bad) ending where a lesson is learned?
- Title of the story will be the name of the tarot card. 
- If the images are public domain, make the image for them be the original tarot card. Otherwise maybe just an image I can find online, or I draw my own.

Tarot cards and their meanings here: https://www.alittlesparkofjoy.com/tarot-cards-list/

Just do the major arcana ones:
- [ ] [0. The Fool](https://www.alittlesparkofjoy.com/tarot-cards-list/#0-the-fool)
- [ ] [1. The Magician](https://www.alittlesparkofjoy.com/tarot-cards-list/#1-the-magician)
- [ ] [2. The High Priestess](https://www.alittlesparkofjoy.com/tarot-cards-list/#2-the-high-priestess)
- [ ] [3. The Empress](https://www.alittlesparkofjoy.com/tarot-cards-list/#3-the-empress)
- [ ] [4. The Emperor](https://www.alittlesparkofjoy.com/tarot-cards-list/#4-the-emperor)
- [ ] [5. The Hierophant](https://www.alittlesparkofjoy.com/tarot-cards-list/#5-the-hierophant)
- [x] [6. The Lovers](https://www.alittlesparkofjoy.com/tarot-cards-list/#6-the-lovers)
- [ ] [7. The Chariot](https://www.alittlesparkofjoy.com/tarot-cards-list/#7-the-chariot)
- [ ] [8. Strength](https://www.alittlesparkofjoy.com/tarot-cards-list/#8-strength)
- [ ] [9. The Hermit](https://www.alittlesparkofjoy.com/tarot-cards-list/#9-the-hermit)
- [ ] [10. Wheel Of Fortune](https://www.alittlesparkofjoy.com/tarot-cards-list/#10-wheel-of-fortune)
- [ ] [11. Justice](https://www.alittlesparkofjoy.com/tarot-cards-list/#11-justice)
- [ ] [12. The Hanged Man](https://www.alittlesparkofjoy.com/tarot-cards-list/#12-the-hanged-man)
- [x] [13. Death](https://www.alittlesparkofjoy.com/tarot-cards-list/#13-death)
- [ ] [14. Temperance](https://www.alittlesparkofjoy.com/tarot-cards-list/#14-temperance)
- [ ] [15. Devil](https://www.alittlesparkofjoy.com/tarot-cards-list/#15-devil)
- [ ] [16. The Tower](https://www.alittlesparkofjoy.com/tarot-cards-list/#16-the-tower)
- [x] [17. The Star](https://www.alittlesparkofjoy.com/tarot-cards-list/#17-the-star)
- [x] [18. The Moon](https://www.alittlesparkofjoy.com/tarot-cards-list/#18-the-moon)
- [x] [19. The Sun](https://www.alittlesparkofjoy.com/tarot-cards-list/#19-the-sun)
- [ ] [20. Judgment](https://www.alittlesparkofjoy.com/tarot-cards-list/#20-judgment)
- [ ] [21. The World](https://www.alittlesparkofjoy.com/tarot-cards-list/#21-the-world)

**Long term turn this into an actual printed story/book!**
- Maybe each chapter starts with:
   - The name (e.g. "The Lovers")
   - The picture of the card (maybe the one I drew, or the actual original card if copywrite allows?)
   - Some details/trivia for the card (e.g. **Upright meaning:** Inner voice, unconscious, divine feminine, and security, **Reversed meaning:** Repressed feelings, withdrawal, and silence, **Yes or No:** Yes)
   - Then begin with the content of the story
- Consider if this should also include minor arcana etc. as well? Maybe they don't need as detailed of stories, or you can group them together and have one story for each group??
- Make the stories in order of the original tarots from 0 - 22 or whatever, and then consider editing the stories slightly to fit together in the same "universe"?

**Comment by ShaneBonkowski** [comment]
See https://github.com/ShaneBonkowski/shane-bonkowski-dot-com/issues/13
