### ISSUE TITLE
Final To-Do for Boids Game

### ISSUE THREAD

**Issue by ShaneBonkowski** [ShaneBonkowski/ShanesGames#39]
- [x] Make Leader boid by default disappear when pointer is up (can have it subscribe to the events that already exist for checking if the leader is activated)
    - Add a disabled attr to boids, and when they are disabled they are excluded from physics sim, hidden, and not considered by other boids as they loop through the boids list to do any position etc. updates
- [x] Add a toggle to disable / enable leader boid in settings (enabled by default)
- [x] Add images for the settings screen

**Comment by ShaneBonkowski** [comment]
Other ideas:
- [x] Have the boid behaviors for good boids and bad boids such that similar boid types flock together, and if boid types oppose, good boids run from bad boids and bad boids chase good boids
- [x] For the event where we subscribe to make the main boid “activated” we should replace that with an event that lives in the main game. Something where we reference if the “pointer held down on canvas” or similar

**Comment by ShaneBonkowski** [comment]
- [x] The way boids bounce back n forth on edges when predator chases prey makes me think something about the distance and direction calculation is not working with screen edges. May have something to do with how we decide to go towards or away from center of mass, and whether or not center of mass direction takes into account "pacman-style" screen edge. May need to either instantaneously change pos / vel, or take into account the direction somehow by using dy and dx instead of position - otherPosition etc.

**Comment by ShaneBonkowski** [comment]
- [x] Fix issue where when leader spawns in on phone his location is at his last location instead of current finger loc. Location does not update until finger moves. This line should have fixed it but didnt

```
// Hide / reveal leader on pointer up / down
      document.addEventListener(
        "pointerholdclick",
        function () {
          // Enable leader boid if ui menu is closed
          if (!this.scene.uiMenuOpen) {
            this.enable();

            // Make sure leader is on mouse location
            this.graphic.x = pointer.worldX;
            this.graphic.y = pointer.worldY;
          }
        }.bind(this),
        { capture: true }
      );
```

**Comment by ShaneBonkowski** [comment]
- [x] Make boids slightly larger on phone
- [x] Make “black hole reject” subtitle further right on phone (or maybe see if it need further in general for computer etc)
- [x] sliders could be easier to read/see on phone… maybe larger and sharper contrast (white text)?
