### ISSUE TITLE
Flip Tile To-Do

### ISSUE THREAD

**Issue by ShaneBonkowski** [ShaneBonkowski/ShanesGames#55]
- [x] Add a reset button
- [x] Add a skip to next puzzle button
- [x] Add support for even-numbered square puzzles (need to change how position of tiles are calced)
- [x] Add a difficulty value that can increase or decrease at the press of buttons 2x2 matrix, 3x3, 4x4, 5x5 (look at ipad notes for more detail on this)
- [x] Add a reveal solution button which resets the puzzle and then shows which ones you need to press to solve it
- [x] Add pointer on hover of tiles and make them grow in size when hovered as an anim
- [x] Add onClick anim for tiles too (maybe they spin or have a cool color thing happen)
- [x] Make it so game does not give you uninteresting puzzles with only a few red for e.g. and also does not give already solved puzzles, and does not give failing puzzles that are unsolveable

**Comment by ShaneBonkowski** [comment]
- [x] Link the youtube video I found that talks about how to solve these in the code where I calculate how to solve these puzzles w/ lin alg
- [x] Add a score system
- [x] Add a cool background

**Comment by ShaneBonkowski** [comment]
- [ ] Fix up the while loop such that it has error handling and tries a new set of tiles if the current one is not solvable
- [ ] Link the youtube video I found that talks about how to solve these in the code where I calculate how to solve these puzzles w/ lin alg

**Comment by ShaneBonkowski** [comment]
- [ ] Add hover pointer / maybe enlarge for the toggle boxes

**Comment by ShaneBonkowski** [comment]
- [x] Spread out tiles more for phone

**Comment by ShaneBonkowski** [comment]
- [ ] Add a daily puzzle option that gives a random configuration that all players can see (random number whose seed is related to the date so that all players have the same one). 
- [ ] Have daily puzzle be like Wordle so you can send it to friends when you solve it. 
- [ ] Have a countdown timer in the top right saying “next daily puzzle in HH:MM” and a button you can click to show the current daily puzzle
- [ ] Need to find a way to alter the share button / text like in Wordle where it shows the pattern when you send it. Maybe it Shows the pattern of the puzzle and how many taps it took you to get it? 
- [ ] Stretch goal: Need some way of it knowing if you’ve already played the daily puzzle so you can't re-do it on accident

**Comment by ShaneBonkowski** [comment]
- [ ] Buttons stay stuck selected after tapping them on phone (like the animation stays enlarged). Fix this
