### ISSUE TITLE
Long Term Flip Tile To-Do

### ISSUE THREAD

**Issue by ShaneBonkowski** [ShaneBonkowski/ShanesGames#68]
- [ ] Add leaderboards? May be in distant future since it will make the website no longer static
- [ ] Add a daily puzzle option that gives a random configuration that all players can see (random number whose seed is related to the date so that all players have the same one). 
    - Have the daily puzzle be like Wordle so you can send it to friends when you solve it. 
    - Need to find a way to alter the share button / text like in Wordle where it shows the pattern when you send it. Maybe it Shows the pattern of the puzzle and how many taps it took you to get it? 
- [ ] Have a countdown timer in the top right saying “next daily puzzle in HH:MM” and a button you can click to show the current daily puzzle
- [ ] Stretch goal: Need some way of it knowing if you’ve already played the daily puzzle so you can't re-do it on accident. May require accounts be made or similar... maybe just locally store this in local storage for now

**Comment by ShaneBonkowski** [comment]
- [ ] Make UI adapt to screen size changes better. Right now if you scale the screen the UI is slightly broken
