### ISSUE TITLE
Start Tracking Player and Site Analytics

### ISSUE THREAD

**Issue by ShaneBonkowski** [ShaneBonkowski/ShanesGames#80]
- Would be nice to track how many people have played each game, how long they have played, etc. 
- Track easy things like page visits for each page too.
- Use [Google Analytics](https://analytics.google.com/analytics/web/?pli=1#/p440155190/reports/intelligenthome) to do the tracking. I already made an account and just need to follow the instructions linked on the `Get Tagging Instructions` button. Note that I will need to add the code to the head of every html page I want to track (maybe make a function to embed this in the html files). NOTE: the key I use for tracking should not be public, so I may need to get creative with how I include this in the source code...

**Comment by ShaneBonkowski** [comment]
So GitHub has something called `secrets` and `environment variables` [more info here](https://docs.github.com/en/actions/security-guides/using-secrets-in-github-actions) that can be accessed via GitHub Actions when building my website before deployment. Pretty much I need to add my Google Analytics key as a secret so that I can access it as a variable in a GitHub Action, and then overwrite the existing html documents to reference that key on build. By being a secret, only I can see it.

In doing this, I will also need to change it so that instead of automatically building and serving my website whenever I push to main branch, I need to create a custom workflow that does this all for me every time I push to main, but also in the middle of the build process applies the Google Analytics key and any other things I'd like to be applied pre-build. This means on the `pages` section, I change it from Source: `deploy from a branch`, to `GitHub Actions`. The file I create to run the actions is a `build_and_deploy.yml` file that will need to be located in a folder called `.github/workflows`. It will look something like:

```
name: Deploy Website

on:
  push:
    branches: 
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Dependencies
        run: npm install

      # Modify HTML files to add Google Analytics key
      - name: Add Google Analytics Key
        run: |
          # Replace 'YOUR_GOOGLE_ANALYTICS_KEY' with your actual Google Analytics key environment variable name
          sed -i 's/YOUR_GOOGLE_ANALYTICS_KEY/${{ secrets.GOOGLE_ANALYTICS_KEY }}/g' index.html
          # Repeat this command for any other HTML files that need the key added (OR! see if I can create code to query and do this to all files ending in .html?)

      - name: Build Website
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build

```

NOTE: I should make documentation for this in a `README` in the folder where this workflow is located so that it is obvious that this runs every time I commit to main, and that any private things I need to add that only I should see such as API keys are to be added as a secret or environment variable in GitHub. This documentation should make it clear to any developer or user coming in what they need to do in order to publish their own websites. Basically describe the above steps at a high level in the README.

The beauty in this approach with the building and making a custom workflow to do the build is that if I ever wanted to change to a different provider than GitHub, I could just change the location that my build file is sent to. This should also be included in the README. Basically document as much as possible about this so that it is obvious what I need to do in the future to add to or modify this website

**Comment by ShaneBonkowski** [comment]
Add a readme explaining that analytics are tracked on Google Analytics with a link to Google Analytics. it should also remind myself that the key for this is located in the `secret` variables in GitHub. Also that the analytics are added to each html page in the GitHub Actions yml file, so as I add more html pages I will need to add them to the yml file so that they have analytics.

NOTE: Maybe I could somehow query all .html pages in order to add these to analytics without specifying the exact name?

Have a specific section in the GitHub Actions readme explaining that any API keys etc. that only I should see should be referenced and added using secrets and GitHub Actions

**Comment by ShaneBonkowski** [comment]
Order of operations:
- [x] Set up file structure and README files described above
- [x] Get GitHub Actions working to publish the site as it works currently, except with GitHub Actions.
- [x] Create the secret variable for the Google Analytics and make sure it is actually something only I can see (or at least people with admin privileges on this repo?)
- [x] Get Google Analytics implementation working so that every html file has the code added to it on build
- [x] Start tracking the stats I want to for each page!

**Comment by ShaneBonkowski** [comment]
Close this after manually verifying I can see stats!! May take 48 hours
